###

GET http://localhost:4000/api/wishList/all

###

GET http://localhost:4000/api/wishList/userWishLists/64fbf5b43c612b13b658d6eb
###

GET http://localhost:4000/api/user/profile/64fbf5b43c612b13b658d6eb

###

GET http://localhost:4000/api/shopItem/64fbf1473c612b13b658d6df

###